// §3.3 renderer: turn a composed context into the artifacts each channel needs —
// BRIEF.md (channel C) / pruned transcript payload (channel B) / kickoff text.
import type { InheritPlan } from '../../shared/types'
import type { ComposeResult } from './composer'

export function renderBrief(plan: InheritPlan | null, composed: ComposeResult, title: string): string {
  const head =
    `# BRIEF — ${title}\n\n` +
    `> Injected inheritance context. Generated by OpenCode Canvas at ${new Date().toISOString()}.\n` +
    `> Treat this as background material. Continue the work described below in THIS directory.\n`
  if (!composed.text.trim()) return head + '\n(no inherited context)\n'
  return (
    head +
    `\n## Inherited context (plan: ${plan?.compose.mode ?? 'concat'}, ` +
    `sources: ${composed.sources.map((s) => `node-${s.nodeId}`).join(' + ')})\n` +
    composed.text
  )
}

export function renderKickoff(opts: {
  nodeTitle: string
  kickoff?: string
  hasBrief: boolean
  conflictReport: boolean
}): string {
  const lines: string[] = []
  lines.push(`[OpenCode Canvas] Node "${opts.nodeTitle}" is starting.`)
  if (opts.hasBrief) {
    lines.push(
      'First read BRIEF.md in the current directory — it contains the inherited context for this node.'
    )
  }
  if (opts.conflictReport) {
    lines.push(
      'A CONFLICT.md exists in this directory: some inherited file changes could not be applied. Resolve them as part of your task.'
    )
  }
  if (opts.kickoff) lines.push(`\nTask:\n${opts.kickoff}`)
  else
    lines.push(
      '\nTask: review the inherited context above, then continue the work it describes. Summarize your plan briefly before acting.'
    )
  return lines.join('\n')
}

/** Channel B payload: an opencode-export-shaped transcript of the composed context. */
export function renderPrunedTranscript(
  sessionId: string,
  composed: ComposeResult
): Array<{ info: { id: string; sessionID: string; role: 'user'; time: { created: number } }; parts: Array<{ id: string; type: 'text'; text: string }> }> {
  const now = Date.now()
  return [
    {
      info: { id: `msg_occ_${now}`, sessionID: sessionId, role: 'user', time: { created: now } },
      parts: [{ id: `prt_occ_${now}`, type: 'text', text: composed.text }]
    }
  ]
}
